name: nix flake check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: [native-x86_64-linux, bigger-parallel]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-home@a4a889b9c11347ff52afd33bd731618604bbb8b1 # v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          gpg-key-id: ${{ vars.GPG_KEY_ID }}

      - run: nix fmt -L --accept-flake-config -- --ci
      - run: nix flake check -L --accept-flake-config
