name: nix flake check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: [native-x86_64-linux, bigger-parallel]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-home@85c04dfa32da72ea8d9d9058601121a7194672fa
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          gpg-key-id: ${{ vars.GPG_KEY_ID }}

      - run: nix fmt -L --accept-flake-config -- --ci
      - run: nix flake check -L --accept-flake-config
